[build]
target = "armv7-linux-androideabi"

[target.armv7-linux-androideabi]
linker = "C:\\Users\\marci\\AppData\\Local\\Android\\Sdk\\ndk\\27.0.12077973\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi35-clang.cmd"